### ISSUE TITLE
Camera Flash Not Persistent When 'Taking a Picture'  

### ISSUE THREAD

**Issue by luxmanifestus** [glacier-modding/H3-Community-Patches#123]
When 'taking a picture' with the camera (pausing the game with the camera to examine the subject), the flash does not persist upon the subject; the flash seems to occur before the still frame instead of during it. The flash is necessary when viewing subjects in lowlight (like suspects during a showdown, to identify descriptive properties and tells).

**Comment by Ocean-Minnow** [comment]
If I'm not mistaken, the flash is applied to the screen as a sort of overlay. It seems to be intended as a sort of visual flavor rather than an actual in-world effect (and would make it very hard to see subjects in high light if it were) so I'm closing this for now as not being in the scope of this mod.

**Comment by AnthonyFuller** [comment]
If anyone is wondering, it's a post processing effect.

**Comment by Ocean-Minnow** [comment]
Ah, that's the word I was looking for!
