### ISSUE TITLE
Keypad Code to ICA Facility Maintenance Corridor Entrance is Incorrect

### ISSUE THREAD

**Issue by luxmanifestus** [glacier-modding/H3-Community-Patches#138]
The keypad code to access the ICA facility maintenance corridors is incorrect. It has the code to enter Hush's Block facility (2552) when it should have the code to enter the ICA facility (0118). 
![ICA Hatch](https://github.com/user-attachments/assets/d4f5fcc6-920d-485f-8c74-153c7f6dc0c8) 
![ICA Hatch 2](https://github.com/user-attachments/assets/7c2b68d1-911c-417d-9269-6f02f4c77fc9)

**Comment by dribbleondo** [comment]
I get the feeling it's because it's in Hush's part of the map I admit, it doesn't make much sense otherwise, but I do feel there is _some_ logic to it.

**Comment by Ocean-Minnow** [comment]
This is the hatch that Hush uses to sneak in and out of the ICA Facility. It's mentioned in-level that he's sneaking out to work on his "project", and so it's logical to assume that this hatch is how he does so, and that he set the password.

**Comment by luxmanifestus** [comment]
So Hush sets up access so anyone who works at the Block can enter the ICA facility? If Hush is granted access to the ICA facility, he would be given the access code (0118). Why would he have his own code? The access point surly isn't secret; it's obvious to anyone who enters the maintenance corridor. If it is an ICA asset, they would have control over the access code and not allow Hush to change it; they would simply give him the facility access code.

**Comment by Ocean-Minnow** [comment]
> If Hush is granted access to the ICA facility, he would be given the access code (0118). Why would he have his own code?

So that Royce can't find out what his project really is. Even if Royce were to crawl inside the vents for some reason, she wouldn't be able to just punch in the ICA code and climb the ladder.

> The access point surly isn't secret; it's obvious to anyone who enters the maintenance corridor.

I originally had a longer message here about how they had given the hatch the implication of being hidden without making it unreasonable for the player to find it, but then I found that the challenge "Quite a Hatch", awarded for opening this hatch, has the description "Unlock the secret hatch." This implies that the hatch is indeed meant to be a secret.

> If it is an ICA asset, they would have control over the access code and not allow Hush to change it

Hush probably didn't ask before changing it. He's in charge of this site, he'd have the power to do that. Who will stop him? Who outranks him? Only Board Members like Mr. Pritchard, who's possibly coming to tour the facility *because* Hush keeps disappearing for extended periods of time.

(Or maybe because of Berlin. Both are given as possibilities and I don't think the game ever confirms which it is. It could even be a bit of both, but that's beside the point.)

**Comment by luxmanifestus** [comment]
For the sake of argument, it appears from the in-game prompt that the hatch is an escape hatch, presumably known to the facility and that the exterior hatch is only "secret" to the wider world at large, as they would not like it known where it leads. It's on Block property and presumable known to them but that would not entitle them to access it. The escape hatch prompt is not secured, being a safety mechanism that is presumably available to anyone. Using the escape hatch does grant access to the Block after passing by guarded check points, with only one path being secured by a locked door, but this is probably just a design choice to serve the gameplay rather than the narrative. 
![Escape Hatch](https://github.com/user-attachments/assets/83f9c904-8b11-48ce-9d78-d0cc791de997)
